// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6MRX2ybc8qzPKuYd4sNVEW64DLnNA_Ig',
    appId: '1:673698221056:web:b851ace945dffda1a19ce5',
    messagingSenderId: '673698221056',
    projectId: 'tiny-plan-d3a11',
    authDomain: 'tiny-plan-d3a11.firebaseapp.com',
    storageBucket: 'tiny-plan-d3a11.appspot.com',
    measurementId: 'G-PQ0F86HS33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADJWVa81Oy0OiYjjcgs3ztahGW91un-mk',
    appId: '1:673698221056:android:45d432ea9bef2d73a19ce5',
    messagingSenderId: '673698221056',
    projectId: 'tiny-plan-d3a11',
    storageBucket: 'tiny-plan-d3a11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6RocY-X27Ffn7GsSYzH0fStjJi89dmo',
    appId: '1:673698221056:ios:5dc64e28c525c92aa19ce5',
    messagingSenderId: '673698221056',
    projectId: 'tiny-plan-d3a11',
    storageBucket: 'tiny-plan-d3a11.appspot.com',
    iosClientId: '26954900915-0lqmv5qafbu040g3ce6mnimd2kv3upd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinyPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN6RocY-X27Ffn7GsSYzH0fStjJi89dmo',
    appId: '1:673698221056:ios:5dc64e28c525c92aa19ce5',
    messagingSenderId: '673698221056',
    projectId: 'tiny-plan-d3a11',
    storageBucket: 'tiny-plan-d3a11.appspot.com',
    iosClientId: '673698221056-bgmg725en0ioa3f3q50pr060gs33h2m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinyPlan.RunnerTests',
  );
}
